// React/test-react-ts/src/components/layout/index.tsx
import React, {useEffect, useState} from 'react'
import {
    MenuFoldOutlined,
    UploadOutlined,
    UserOutlined,
    VideoCameraOutlined,
    MenuUnfoldOutlined
} from "@ant-design/icons";
import { Button, Layout, Menu, theme, Input } from "antd";
import { Outlet, Link, useLocation } from "react-router-dom";
import {IItemProps, IMenuProps} from './type.ts'
import './index.css'

const { Header, Sider, Content } = Layout;




function getItem({label, path, key , children, icon = <UserOutlined />}: IItemProps) {
    return {
      key,
      icon,
      children,
      label: (
        <Link to={path} state={{state1: 'Test State'}}>
            {label}
        </Link>
      ),
    };
}

const menuList: IMenuProps[] = [
    {
        title: '首页',
        key: '/',
        path: '/',
        children: [
            {
              title: 'home',
              key: 'home',
              path: '/home',
            },
            {
                title: 'swiper',
                key: 'swiper',
                path: '/swiper',
            },
            {
              title: 'about',
              key: 'about',
              path: '/about',
            },
            {
              title: 'threelevel',
              key: 'threelevel',
              path: '/threelevel',
            },
            {
              title: 'useparams',
              key: 'useparams',
              path: '/useparams/id/name/content',
            },
            {
              title: 'usenavigate',
              key: 'usenavigate',
              path: '/usenavigate',
            },
            {
              title: 'echarts',
              key: 'echarts',
              path: '/echarts',
            }
        ]
    }
]
function generateItems (items: IMenuProps[]): any[] {
    return items.map((item: IMenuProps) => {
        if (item.children) {
            return getItem({
                label:item.title, 
                path: item.key,
                key:item.path, 
                children:generateItems(item.children)
            });
        }
        return getItem({
            label: item.title,
            key: item.key,
            path: item.path,
        });
    });
}

export default function Index() {
    const [collapsed, setCollapsed] = useState(false);
    const {
      token: { colorBgContainer },
    } = theme.useToken();
    const location = useLocation();
    const [menuKey, setMenuKey] = useState('/home');

    useEffect(() => {
        // console.log('location', location.pathname.split('/'));
        setMenuKey(location.pathname.split('/')[1]);
    }, [location]);

    return (
        <Layout className="layout_wrap" style={{height: '100vh'}}>
        <Sider trigger={null} collapsible collapsed={collapsed}>
          <div className="logo" />
          <Menu
            theme="dark"
            mode="inline"
            selectedKeys={[menuKey]}
            items={generateItems(menuList[0]?.children || [])}
          />
        </Sider>
        <Layout>
          <Header
            style={{
              padding: 0,
              background: colorBgContainer,
            }}
          >
            <Button
              type="text"
              icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
              onClick={() => setCollapsed(!collapsed)}
              style={{
                fontSize: "16px",
                width: 64,
                height: 64,
              }}
            />
          </Header>
          <Content
            style={{
              margin: "24px 16px",
              padding: 24,
              minHeight: 280,
              background: colorBgContainer,
            }}
          >
              <Outlet />
          </Content>
        </Layout>
      </Layout>
    )
}

// Vue/vue-test/src/components/Layout.vue
<script setup>
import { ref, onMounted } from 'vue'
import * as echarts from 'echarts'
import BarChart from './BarChart.vue'
import {Tree} from 'ant-design-vue'
import {RouterView, RouterLink} from 'vue-router'

defineProps({
  msg: String,
})

const onCollapse = (collapsed, type) => {
  console.log(collapsed, type);
};
const onBreakpoint = broken => {
  console.log(broken);
};
const selectedKeys = ref(['1']);
</script>

<template>
  <a-layout>
    <a-layout-sider
      breakpoint="lg"
      collapsed-width="0"
      @collapse="onCollapse"
      @breakpoint="onBreakpoint"
      :style="{ height: '100vh' }"
    >
      <div class="logo" />
      <a-menu v-model:selectedKeys="selectedKeys" theme="dark" mode="inline">
        <a-menu-item key="1">
          <RouterLink to="/about">
            <span class="nav-text">about</span>
          </RouterLink>
        </a-menu-item>
        <a-menu-item key="2">
          <RouterLink to="/user">
            <span class="nav-text">user</span>
          </RouterLink>
        </a-menu-item>
      </a-menu>
    </a-layout-sider>
    <a-layout>
      <a-layout-header :style="{ background: '#fff', padding: 0 }">
        header11
      </a-layout-header>
      <a-layout-content :style="{ margin: '24px 16px 10px' }">
        <a-layout class="content-wrap">
          <RouterView />
        </a-layout>
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>

<style scoped>
#components-layout-demo-responsive .logo {
  height: 32px;
  background: rgba(255, 255, 255, 0.2);
  margin: 16px;
}

.site-layout-sub-header-background {
  background: #fff;
}

.site-layout-background {
  background: #fff;
}

[data-theme='dark'] .site-layout-sub-header-background {
  background: #141414;
}

.content-wrap {
  width: 100%;
  height: 100%;
  background-color: #fff;
}



</style>
