// React/test-react/src/components/layout/index.jsx
import React, { useState } from "react";
import {
  MenuFoldOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  MenuUnfoldOutlined
} from "@ant-design/icons";
import { Button, Layout, Menu, theme, Input } from "antd";
import './index.less';
import { Outlet, Link } from "react-router-dom";



const { Header, Sider, Content } = Layout;

function getItem(label, key, children, icon = <UserOutlined />) {
    return {
      key,
      icon,
      children,
      label: (
        <Link to={key}>
            {label}
        </Link>
      ),
    };
}
const menuList = [
    {
        title: '首页',
        key: '/',
        path: '/',
        children: [
            {
                title: 'state',
                key: '/state',
                path: '/state',
            
            },
            {
                title: 'usecallback',
                key: '/usecallback',
                path: '/usecallback',
            },
            {
                title: 'class',
                key: '/class',
                path: '/class',
            },
            {
                title: 'useState',
                key: '/usestate',
                path: '/usestate',
            },
            {
                title: 'useMemo',
                key: '/usememo',
                path: '/usememo',
            },
            {
                title: 'useContext',
                key: '/usecontext',
                path: '/usecontext',
            }
        ]

    }
]
function generateItems (items) {
    return items.map((item) => {
        if (item.children) {
            return getItem(item.title, item.path, generateItems(item.children));
        }
        return getItem(item.title, item.path);
    });
}

const LayoutCom = () => {
  const [collapsed, setCollapsed] = useState(false);
  const {
    token: { colorBgContainer },
  } = theme.useToken();
  console.log('render');


  return (
    <Layout className="layout_wrap" style={{height: '100vh'}}>
      <Sider trigger={null} collapsible collapsed={collapsed}>
        <div className="logo" />
        <Menu
          theme="dark"
          mode="inline"
          defaultSelectedKeys={["1"]}
          items={generateItems(menuList[0].children)}
        />
      </Sider>
      <Layout>
        <Header
          style={{
            padding: 0,
            background: colorBgContainer,
          }}
        >
          <Button
            type="text"
            icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
            onClick={() => setCollapsed(!collapsed)}
            style={{
              fontSize: "16px",
              width: 64,
              height: 64,
            }}
          />
        </Header>
        <Content
          style={{
            margin: "24px 16px",
            padding: 24,
            minHeight: 280,
            background: colorBgContainer,
          }}
        >
            <Outlet />
            {/* <Input /> */}
        </Content>
      </Layout>
    </Layout>
  );
};

export default LayoutCom;

// Vue/vue-test/src/components/Layout.vue
<script setup>
import { ref, onMounted } from 'vue'
import * as echarts from 'echarts'
import BarChart from './BarChart.vue'
import {Tree} from 'ant-design-vue'
import {RouterView, RouterLink} from 'vue-router'

defineProps({
  msg: String,
})

const onCollapse = (collapsed, type) => {
  console.log(collapsed, type);
};
const onBreakpoint = broken => {
  console.log(broken);
};
const selectedKeys = ref(['1']);
</script>

<template>
  <a-layout>
    <a-layout-sider
      breakpoint="lg"
      collapsed-width="0"
      @collapse="onCollapse"
      @breakpoint="onBreakpoint"
      :style="{ height: '100vh' }"
    >
      <div class="logo" />
      <a-menu v-model:selectedKeys="selectedKeys" theme="dark" mode="inline">
        <a-menu-item key="1">
          <RouterLink to="/about">
            <span class="nav-text">about</span>
          </RouterLink>
        </a-menu-item>
        <a-menu-item key="2">
          <RouterLink to="/user">
            <span class="nav-text">user</span>
          </RouterLink>
        </a-menu-item>
      </a-menu>
    </a-layout-sider>
    <a-layout>
      <a-layout-header :style="{ background: '#fff', padding: 0 }">
        header11
      </a-layout-header>
      <a-layout-content :style="{ margin: '24px 16px 10px' }">
        <a-layout class="content-wrap">
          <RouterView />
        </a-layout>
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>

<style scoped>
#components-layout-demo-responsive .logo {
  height: 32px;
  background: rgba(255, 255, 255, 0.2);
  margin: 16px;
}

.site-layout-sub-header-background {
  background: #fff;
}

.site-layout-background {
  background: #fff;
}

[data-theme='dark'] .site-layout-sub-header-background {
  background: #141414;
}

.content-wrap {
  width: 100%;
  height: 100%;
  background-color: #fff;
}



</style>
